### ISSUE TITLE
Title not correctly parsed in notes’ URLs

### ISSUE THREAD

**Issue by xplosionmind** [shorty25h0r7/jekyll-wikilinks#5]
After opening a ton of feature requests issues (sorry if they were too many) I now unfortunately have to report a bug/malfunctioning.

Every URL parsed by this plugin corresponds to `/:title`. Is it my fault? Please do not tell me I have to set a `title: "Some title"` in the front matter of every single one of my 150 `.md` files in the collection `jekyll-wikilinks` works in.

What should I do?

Thanks a lot.

Best,  
T

**Comment by shorty25h0r7** [comment]
Yes, currently you have to have a `title:` attribute for every note (and a `permalink:`). It's in the github README, but I will update it to be a bit more accurate in its verbiage.

This is because of the way I am currently using the plugin in my own (currently unreleased) template, which (atm) depends on some of [Dendron's](https://github.com/dendronhq/dendron) default configs, which auto-populate note frontmatter in this fashion:

```
---
id: <a-uuid>
title: Note Title
desc: ''
updated: <epoch-time>
created: <epoch-time>
---
```

The `jekyll-wikilinks` plugin specifically relies on  this`title:` and I am automatically adding an explicitly defined `permalink:` elsewhere in my template.

I ended up making the `title:` mandatory to get the plugin out sooner. I will close this issue, but feel free to open up another feature request to change this. 🙂

(And the feature requests are good -- it helps a lot to have others test and provide well described write-ups. Keep it up! 👍)
